#!/usr/local/bin/bash

# make the executable accessible
if [[ "$(echo "${PATH}" | grep './node_modules/.bin')" == "" ]]; then
  echo "Export ./node_modules/.bin to PATH"
  PATH=./node_modules/.bin:$PATH
fi

export PATH
