#!/usr/local/bin/bash

__load "${BASH_SOURCE[0]}" "shlogging"

# make the executable accessible
if [[ "$(echo "${PATH}" | grep './node_modules/.bin')" == "" ]]; then
  _info "Export $(_green "./node_modules/.bin") to PATH"
  PATH=./node_modules/.bin:$PATH
fi

export PATH
